#!/usr/bin/env python3
"""Install macos-sandbox-testing into a Go module.

Goal: make direct `go test ./...` runs apply an in-process Seatbelt sandbox
in every package test binary.

Implementation strategy:

1) Install a small cgo-enabled helper package under tools/ that compiles and
   links `SandboxTestingBootstrap.c`.
2) For each Go package directory under the module, generate a `_test.go` file
   that blank-imports the helper package to force linkage.

No third-party dependencies (stdlib only).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path


_INSTALL_MARKER = ".macos-sandbox-testing-installed.json"
_GENERATED_MARKER_LINE = "// macos-sandbox-testing: generated"


@dataclass(frozen=True)
class InstallManifest:
    module_path: str
    install_dir: str
    generated_files: list[str]


def _read_text(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _write_text(p: Path, s: str, *, dry_run: bool) -> None:
    if dry_run:
        return
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")


def _dump_json(obj: object) -> str:
    return json.dumps(obj, indent=2, sort_keys=True) + "\n"


def _relpath(from_dir: Path, to_path: Path) -> str:
    return os.path.relpath(str(to_path), str(from_dir)).replace(os.sep, "/")


def _parse_go_mod_module(go_mod: Path) -> str:
    for ln in _read_text(go_mod).splitlines():
        s = ln.strip()
        if not s or s.startswith("//"):
            continue
        if s.startswith("module "):
            return s.split(None, 1)[1].strip()
        break
    raise RuntimeError(f"Failed to find module path in {go_mod}")


def _is_ignored_dir(p: Path, *, project_root: Path, install_dir: Path) -> bool:
    rel = _relpath(project_root, p)
    parts = rel.split("/")
    if not parts:
        return False
    top = parts[0]
    if top in {".git", ".build", "node_modules", "vendor", ".venv"}:
        return True
    if p.resolve() == install_dir.resolve():
        return True
    # Do not recurse into installed helper package.
    if install_dir.resolve() in p.resolve().parents:
        return True
    return False


def _discover_go_package_dirs(project_root: Path, install_dir: Path) -> dict[Path, list[Path]]:
    by_dir: dict[Path, list[Path]] = {}
    for p in project_root.rglob("*.go"):
        if not p.is_file():
            continue
        if _is_ignored_dir(p.parent, project_root=project_root, install_dir=install_dir):
            continue
        by_dir.setdefault(p.parent, []).append(p)
    return by_dir


_PKG_RE = re.compile(r"^\s*package\s+([A-Za-z_][A-Za-z0-9_]*)\s*$")


def _package_name_for_dir(files: list[Path]) -> str:
    # Prefer non-test files when available.
    files_sorted = sorted(files, key=lambda p: (p.name.endswith("_test.go"), p.name))
    for f in files_sorted:
        for ln in _read_text(f).splitlines():
            m = _PKG_RE.match(ln)
            if m:
                return m.group(1)
    raise RuntimeError(f"Failed to determine package name from files: {[str(f) for f in files_sorted[:5]]}")


def _install_helper_package(*, project_root: Path, install_dir: Path, force: bool, dry_run: bool) -> list[str]:
    templates_root = Path(__file__).resolve().parent.parent / "assets" / "templates" / "go"
    if not templates_root.exists():
        raise RuntimeError(f"Missing template directory: {templates_root}")

    marker = install_dir / _INSTALL_MARKER
    if install_dir.exists() and not marker.exists() and not force:
        raise RuntimeError(
            f"Refusing to overwrite existing directory (missing marker {marker}).\n"
            f"Pass --force to overwrite: {install_dir}"
        )

    out: list[str] = []
    if dry_run:
        out.append(f"DRYRUN: would ensure directory {install_dir}")
    else:
        install_dir.mkdir(parents=True, exist_ok=True)

    for name in ("bootstrap.go", "SandboxTestingBootstrap.c", "README.md"):
        src = templates_root / name
        dest = install_dir / name
        if dest.exists() and not force:
            out.append(f"SKIP: already exists ({dest})")
            continue
        if dry_run:
            out.append(f"DRYRUN: would write {dest}")
            continue
        shutil.copy2(src, dest)
        out.append(f"OK: wrote {dest}")

    return out


def _generated_test_file_content(*, pkg_name: str, import_path: str) -> str:
    return (
        "//go:build darwin\n\n"
        f"{_GENERATED_MARKER_LINE}\n"
        "// This file is generated by macos-sandbox-testing to force-link the\n"
        "// Seatbelt bootstrap into this package's `go test` binary.\n\n"
        f"package {pkg_name}\n\n"
        f'import _ "{import_path}"\n'
    )


def main() -> None:
    ap = argparse.ArgumentParser(description="Install macos-sandbox-testing into a Go module")
    ap.add_argument("--project-root", required=True, type=Path, help="Go module root containing go.mod")
    ap.add_argument(
        "--install-dir",
        type=Path,
        default=Path("tools") / "macos-seatbelt-testing-go",
        help="Where to install the helper package (relative to --project-root)",
    )
    ap.add_argument("--force", action="store_true", help="Overwrite existing installed files when safe")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    project_root: Path = args.project_root.resolve()
    go_mod = project_root / "go.mod"
    if not go_mod.exists():
        raise SystemExit(f"ERROR: go.mod not found under {project_root}")

    install_dir: Path = args.install_dir
    if install_dir.is_absolute():
        raise SystemExit("ERROR: --install-dir must be a relative path")

    helper_dir = project_root / install_dir
    module_path = _parse_go_mod_module(go_mod)
    helper_import = f"{module_path}/{_relpath(project_root, helper_dir)}"

    for msg in _install_helper_package(project_root=project_root, install_dir=helper_dir, force=args.force, dry_run=args.dry_run):
        print(msg)

    # Discover package dirs.
    dirs = _discover_go_package_dirs(project_root, helper_dir)
    if not dirs:
        print("WARN: no Go packages discovered (no *.go files)")

    generated: list[str] = []
    for d, files in sorted(dirs.items(), key=lambda kv: str(kv[0])):
        # Skip the helper itself.
        if helper_dir.resolve() == d.resolve() or helper_dir.resolve() in d.resolve().parents:
            continue

        out_file = d / "zz_macos_sandbox_testing_bootstrap_test.go"
        if out_file.exists():
            txt = _read_text(out_file)
            if _GENERATED_MARKER_LINE in txt:
                generated.append(_relpath(project_root, out_file))
                continue
            print(f"SKIP: {out_file} exists (not generated by macos-sandbox-testing)")
            continue

        pkg_name = _package_name_for_dir(files)
        content = _generated_test_file_content(pkg_name=pkg_name, import_path=helper_import)
        _write_text(out_file, content, dry_run=args.dry_run)
        print(f"{'DRYRUN:' if args.dry_run else 'OK:'} wrote {out_file}")
        generated.append(_relpath(project_root, out_file))

    marker = helper_dir / _INSTALL_MARKER
    manifest = InstallManifest(
        module_path=module_path,
        install_dir=_relpath(project_root, helper_dir),
        generated_files=generated,
    )
    _write_text(marker, _dump_json(manifest.__dict__), dry_run=args.dry_run)
    print(f"{'DRYRUN:' if args.dry_run else 'OK:'} wrote {marker}")

    if args.dry_run:
        return

    print(
        "\nNext steps:\n"
        "- git status\n"
        "- go test ./... (optionally with SEATBELT_SANDBOX_SELFTEST=1)\n"
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
